// <auto-generated />
using System;
using CashbackBeer.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashbackBeer.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220719222705_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CashbackBeer.Domain.Entities.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("FridayCashback")
                        .HasColumnType("float");

                    b.Property<double>("MondayCashback")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SaturdayCashback")
                        .HasColumnType("float");

                    b.Property<double>("SundayCashback")
                        .HasColumnType("float");

                    b.Property<double>("ThursdayCashback")
                        .HasColumnType("float");

                    b.Property<double>("TuesdayCashback")
                        .HasColumnType("float");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<double>("WednesdayCashback")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FridayCashback = 0.14999999999999999,
                            MondayCashback = 0.070000000000000007,
                            Name = "SKOL",
                            SaturdayCashback = 0.20000000000000001,
                            SundayCashback = 0.25,
                            ThursdayCashback = 0.10000000000000001,
                            TuesdayCashback = 0.059999999999999998,
                            Value = 3.0,
                            WednesdayCashback = 0.02
                        },
                        new
                        {
                            Id = 2,
                            FridayCashback = 0.25,
                            MondayCashback = 0.050000000000000003,
                            Name = "BRAHMA",
                            SaturdayCashback = 0.29999999999999999,
                            SundayCashback = 0.29999999999999999,
                            ThursdayCashback = 0.20000000000000001,
                            TuesdayCashback = 0.10000000000000001,
                            Value = 4.0,
                            WednesdayCashback = 0.14999999999999999
                        },
                        new
                        {
                            Id = 3,
                            FridayCashback = 0.17999999999999999,
                            MondayCashback = 0.029999999999999999,
                            Name = "STELLA",
                            SaturdayCashback = 0.25,
                            SundayCashback = 0.34999999999999998,
                            ThursdayCashback = 0.13,
                            TuesdayCashback = 0.050000000000000003,
                            Value = 5.0,
                            WednesdayCashback = 0.080000000000000002
                        },
                        new
                        {
                            Id = 4,
                            FridayCashback = 0.20000000000000001,
                            MondayCashback = 0.10000000000000001,
                            Name = "BOHEMIA",
                            SaturdayCashback = 0.40000000000000002,
                            SundayCashback = 0.40000000000000002,
                            ThursdayCashback = 0.14999999999999999,
                            TuesdayCashback = 0.14999999999999999,
                            Value = 4.0,
                            WednesdayCashback = 0.14999999999999999
                        });
                });

            modelBuilder.Entity("CashbackBeer.Domain.Entities.FinalSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalCashback")
                        .HasColumnType("float");

                    b.Property<double?>("TotalCashbackValue")
                        .HasColumnType("float");

                    b.Property<double?>("TotalSaleValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FinalSales");
                });

            modelBuilder.Entity("CashbackBeer.Domain.Entities.PartialSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<double?>("CashbackPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("CashbackValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalSaleId")
                        .HasColumnType("int");

                    b.Property<double?>("ValuePartialSale")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("FinalSaleId");

                    b.ToTable("PartialSales");
                });

            modelBuilder.Entity("CashbackBeer.Domain.Entities.PartialSale", b =>
                {
                    b.HasOne("CashbackBeer.Domain.Entities.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashbackBeer.Domain.Entities.FinalSale", "FinalSale")
                        .WithMany("PartialSales")
                        .HasForeignKey("FinalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("FinalSale");
                });

            modelBuilder.Entity("CashbackBeer.Domain.Entities.FinalSale", b =>
                {
                    b.Navigation("PartialSales");
                });
#pragma warning restore 612, 618
        }
    }
}
